import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';
import { createReadStream, statSync } from 'node:fs';
import { extname, join, normalize } from 'node:path';

/* The app and everything it needs to run live in APP_DIR; the repo root holds
   only the sources and tooling that build it.

   app-data/ is 300+ MB of sprites and 2.9 MB of generated `window.X = [...]`
   bundles. Vite must not transform, bundle or copy any of it: the files are
   regenerated by the Python scripts on dev-data and are loaded at runtime as
   classic scripts. This middleware streams them straight off disk, ahead of
   Vite's own transform pipeline, mapping the URL the page asks for onto the
   folder's real home inside APP_DIR. */
export const APP_DIR = 'PDS React Develop';
const RAW_PREFIXES = ['/app-data/', '/Pokerole Core Book/', '/Trainers and Pokemons/'];
const MIME: Record<string, string> = {
    '.js': 'application/javascript', '.json': 'application/json',
    '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
    '.gif': 'image/gif', '.svg': 'image/svg+xml', '.webp': 'image/webp',
    '.pdf': 'application/pdf', '.txt': 'text/plain',
};

function serveAppDataRaw(root: string) {
    return {
        name: 'pokerole-serve-app-data-raw',
        enforce: 'pre' as const,
        configureServer(server: any) {
            server.middlewares.use((req: any, res: any, next: any) => {
                const url = decodeURIComponent((req.url || '').split('?')[0]);
                if (!RAW_PREFIXES.some((p) => url.startsWith(p))) return next();
                const base = join(root, APP_DIR);
                const file = normalize(join(base, url));
                if (!file.startsWith(base)) return next();
                try {
                    if (!statSync(file).isFile()) return next();
                } catch {
                    return next();
                }
                res.setHeader('Content-Type', MIME[extname(file).toLowerCase()] || 'application/octet-stream');
                res.setHeader('Cache-Control', 'no-cache');
                createReadStream(file).pipe(res);
            });
        },
    };
}

/* Every page is a React entry now; nothing is copied in verbatim. Kept as an
   empty list because it is the hook to reach for if a page ever has to ship as
   plain HTML again. */
const LEGACY_PAGES: string[] = [];

/* In dev, ask for a page by the name it has in production.

   The built pages sit at the top of the project — that is where the app is
   opened from — and the dev server would happily serve those static files
   instead of the entries in src/pages/, so `npm run dev` would show the last
   build rather than the code being edited. This rewrites every page name onto
   its source before Vite's static handler ever sees it. */
function devPageAliases(pages: string[]) {
    return {
        name: 'pokerole-dev-page-aliases',
        enforce: 'pre' as const,
        apply: 'serve' as const,
        configureServer(server: any) {
            server.middlewares.use((req: any, _res: any, next: any) => {
                const [path, query] = (req.url || '').split('?');
                const name = path.replace(/^\//, '').replace(/\.html$/, '');
                if (path.endsWith('.html') && pages.includes(name)) {
                    req.url = '/src/pages/' + name + '.html' + (query ? '?' + query : '');
                }
                next();
            });
        },
    };
}


export const PAGES = ['trainer-license', 'pokemon-card', 'gm-screen', 'rolling-table'];
const FIRST_PAGE = PAGES[0];

export default defineConfig(({ command }) => {
    const root = process.cwd();
    const page = process.env.PAGE || FIRST_PAGE;
    return {
        root,
        base: process.env.APP_BASE ?? (command === 'build' ? './' : '/'),
        /* Only the PWA icons. app-data is deliberately NOT in here: Vite would
           copy all 250 MB of it into the build on every run. */
        publicDir: 'public',
        appType: 'mpa',
        plugins: [
            serveAppDataRaw(root),
            devPageAliases(PAGES),
            react(),
            VitePWA({
                registerType: 'prompt',
                injectRegister: null,
                filename: 'sw.js',
                manifestFilename: 'manifest.webmanifest',
                includeAssets: [],
                manifest: {
                    name: "Pokerole Dynamic Sheets",
                    short_name: 'Pokerole Sheets',
                    description: "Character sheets and a wild-encounter builder for the Pokerole TTRPG.",
                    start_url: './trainer-license.html',
                    scope: './',
                    display: 'standalone',
                    orientation: 'any',
                    background_color: '#12151c',
                    theme_color: '#12151c',
                    icons: [
                        { src: './pwa-icon-192.png', sizes: '192x192', type: 'image/png' },
                        { src: './pwa-icon-512.png', sizes: '512x512', type: 'image/png' },
                        { src: './pwa-icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
                    ],
                },
                workbox: {
                    /* Precache the shell only. The sprite library is far too large to
                       precache and is filled in on demand by the runtime rules below. */
                    globPatterns: ['**/*.{js,css,html,svg,woff2}'],
                    globIgnores: ['**/app-data/**', '**/node_modules/**'],
                    maximumFileSizeToCacheInBytes: 6 * 1024 * 1024,
                    navigateFallback: null,
                    runtimeCaching: [
                        {
                            /* The generated databases: big, and they only change on a release. */
                            urlPattern: /\/app-data\/[^/]+\.js$/,
                            handler: 'StaleWhileRevalidate',
                            options: {
                                cacheName: 'pokerole-databases',
                                expiration: { maxEntries: 32, maxAgeSeconds: 60 * 60 * 24 * 90 },
                            },
                        },
                        {
                            /* Sprites and icons, cached the first time they are drawn. */
                            urlPattern: /\/app-data\/.*\.(png|jpe?g|gif|webp|svg)$/,
                            handler: 'CacheFirst',
                            options: {
                                cacheName: 'pokerole-sprites',
                                /* 6104 files match this route — not just the 5237 Pokemon and
                                   item sprites but the two equipment icon catalogues, since the
                                   pattern takes .svg as well. At 4000 the cache evicted art it
                                   was about to want again, so a session that ranged over the dex
                                   kept re-fetching the same tiles. 8000 leaves room to grow. */
                                expiration: {
                                    maxEntries: 8000,
                                    maxAgeSeconds: 60 * 60 * 24 * 180,
                                    /* Evict rather than fail if the origin's quota is hit. */
                                    purgeOnQuotaError: true,
                                },
                            },
                        },
                        {
                            /* The GitHub-raw fallback for any sprite not bundled locally. */
                            urlPattern: /^https:\/\/raw\.githubusercontent\.com\/.*/,
                            handler: 'CacheFirst',
                            options: {
                                cacheName: 'pokerole-remote-sprites',
                                expiration: { maxEntries: 2000, maxAgeSeconds: 60 * 60 * 24 * 180 },
                                cacheableResponse: { statuses: [0, 200] },
                            },
                        },
                        {
                            urlPattern: /^https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/,
                            handler: 'CacheFirst',
                            options: {
                                cacheName: 'pokerole-fonts',
                                expiration: { maxEntries: 32, maxAgeSeconds: 60 * 60 * 24 * 365 },
                                cacheableResponse: { statuses: [0, 200] },
                            },
                        },
                        {
                            urlPattern: /^https:\/\/cdnjs\.cloudflare\.com\/.*/,
                            handler: 'CacheFirst',
                            options: {
                                cacheName: 'pokerole-cdn',
                                expiration: { maxEntries: 64, maxAgeSeconds: 60 * 60 * 24 * 365 },
                                cacheableResponse: { statuses: [0, 200] },
                            },
                        },
                    ],
                },
                devOptions: { enabled: false },
            }),
            {
                /* The entry HTML lives in src/pages/ so it does not sit at the
                   top of the repo pretending to be the built app. Rollup names
                   the emitted file after that path, so put it back at the root
                   of the build, and take the module attributes off the tags
                   Vite injected: the bundle is an iife now, and `type="module"`
                   or `crossorigin` on a file:// page is what triggers the CORS
                   refusal this whole arrangement exists to avoid. */
                name: 'pokerole-flatten-pages',
                apply: 'build' as const,
                enforce: 'post' as const,
                generateBundle(_opts: any, bundle: any) {
                    for (const [key, out] of Object.entries(bundle) as [string, any][]) {
                        if (!key.endsWith('.html')) continue;
                        out.fileName = key.replace(/^src\/pages\//, '');
                        /* `base: './'` was resolved against src/pages/, so
                           every injected URL climbs two levels it no longer
                           needs to now that the file sits at the root. */
                        out.source = String(out.source)
                            .replace(/(src|href)="\.\.\/\.\.\//g, '$1="./')
                            /* `type="module"` implied defer. A classic script
                               does not, and Vite injects it into <head> — so
                               without this it runs before <div id="root">
                               exists and React aborts on a missing container. */
                            .replace(/\s+type="module"/g, ' defer')
                            .replace(/\s+crossorigin(?=[\s>])/g, '');
                        delete bundle[key];
                        bundle[out.fileName] = out;
                    }
                },
            },
            {
                /* Copy the not-yet-converted pages into the build untouched. */
                name: 'pokerole-copy-legacy-pages',
                apply: 'build' as const,
                async generateBundle(this: any) {
                    const { readFile } = await import('node:fs/promises');
                    for (const legacy of LEGACY_PAGES) {
                        try {
                            this.emitFile({
                                type: 'asset',
                                fileName: legacy,
                                source: await readFile(join(root, legacy), 'utf8'),
                            });
                        } catch { /* already converted, or not present */ }
                    }
                },
            },
        ],
        build: {
            outDir: 'dist-pwa',
            /* Pass one clears it; the other two add to it. */
            emptyOutDir: page === FIRST_PAGE,
            target: 'es2022',
            assetsDir: 'assets',
            rollupOptions: {
                input: { [page]: join(root, 'src/pages', page + '.html') },
                output: {
                    /* Classic script, not an ES module.

                       This is the whole reason the build runs once per page:
                       Rollup will not code-split an iife, and an ES module is
                       exactly what a browser refuses to load over file://
                       ("blocked by CORS policy ... origin 'null'"). The app has
                       always been opened by double-clicking the .html, so the
                       bundle has to be a plain script with nothing left to
                       fetch at startup. */
                    format: 'iife' as const,
                    inlineDynamicImports: true,
                    entryFileNames: 'assets/[name]-[hash].js',
                },
            },
        },
        server: {
            port: 5173,
            watch: { ignored: ['**/app-data/**', '**/dist/**', '**/dist-pwa/**', '**/Trainers and Pokemons/**', '**/gifs/**', '**/Pokerole Core Book/**'] },
        },
    };
});
