import { DATA_BASE, IMG_BASE } from './paths';
import type {
    AppData, PokedexEntry, MoveEntry, ItemEntry, AbilityEntry, NatureEntry,
    EquipIcon, SpriteFrames,
} from './types';

/* Loads the generated bundles out of app-data/.

   They are classic scripts, not modules, and they are regenerated by the Python
   scripts on the dev-data branch — so they are loaded as-is rather than
   imported, and nothing here may require a change to their contents. That also
   keeps 2.9 MB of Pokédex out of the app bundle: it is fetched once and then
   held by the service worker.

   Two flavours of global to read back:
     - pokedex/moves/items/abilities/natures/version assign to `window.X`
     - equip-icons and sprite-frames use a top-level `const`, which lands in the
       global *lexical* environment and is therefore NOT a property of window.
       Indirect eval at global scope is the only way to reach those. */

const BUNDLES = [
    'pokedex-db.js', 'moves-db.js', 'items-db.js', 'abilities-db.js', 'natures-db.js',
    'equip-icons-db.js', 'equip-icons-mono-db.js', 'sprite-frames-db.js', 'version.js',
] as const;

function injectScript(src: string): Promise<void> {
    return new Promise((resolve, reject) => {
        const el = document.createElement('script');
        el.src = src;
        el.async = false;              // keep them in order, like document.write did
        el.onload = () => resolve();
        el.onerror = () => reject(new Error('Could not load ' + src));
        document.head.appendChild(el);
    });
}

/** Read a script-level `const` binding, which never becomes a window property. */
function readLexical<T>(name: string): T | undefined {
    try {
        return (0, eval)(`typeof ${name} !== 'undefined' ? ${name} : undefined`) as T | undefined;
    } catch {
        return undefined;
    }
}

let pending: Promise<AppData> | null = null;

/** Loads every bundle once; later callers get the same promise. */
export function loadAppData(): Promise<AppData> {
    if (pending) return pending;
    pending = (async () => {
        for (const file of BUNDLES) await injectScript(DATA_BASE + file);
        const w = window as unknown as Record<string, unknown>;
        return {
            pokemon: (w.ALL_POKEMON as PokedexEntry[]) ?? [],
            moves: (w.ALL_MOVES as MoveEntry[]) ?? [],
            items: (w.ALL_ITEMS as ItemEntry[]) ?? [],
            abilities: (w.ALL_ABILITIES as AbilityEntry[]) ?? [],
            natures: (w.ALL_NATURES as NatureEntry[]) ?? [],
            equipIcons: readLexical<EquipIcon[]>('EQUIP_ICONS') ?? [],
            equipIconsMono: readLexical<EquipIcon[]>('EQUIP_ICONS_MONO') ?? [],
            equipIconDir: readLexical<string>('EQUIP_ICON_DIR') ?? (DATA_BASE + 'dnd-item-icons-by-gwill-main/Library/'),
            equipIconMonoDir: readLexical<string>('EQUIP_ICON_MONO_DIR') ?? (DATA_BASE + 'dnd-monochrome-icons/'),
            spriteFrames: readLexical<SpriteFrames>('SPRITE_FRAMES') ?? {},
            version: (w.APP_VERSION as string) ?? '',
            repo: (w.APP_REPO as string) ?? '',
        };
    })();
    return pending;
}

/* Is the app-data folder actually there? The bundles above can still be in
   memory from an earlier load after the folder is deleted, so probe a known
   sprite with a cache-buster. Run on load AND whenever a working folder is
   opened. */
export function checkAppDataAsset(): Promise<boolean> {
    return new Promise((resolve) => {
        const img = new Image();
        img.onload = () => resolve(true);
        img.onerror = () => resolve(false);
        /* The cache-buster is what makes this a real check rather than a
           re-read of whatever the browser kept. But once a service worker is
           controlling the page it is also what BREAKS the check: the busted URL
           no longer matches the sprite cache rule (whose pattern ends at the
           extension), so offline the probe fails and the page claims app-data is
           missing while the worker is holding every byte of it. With a worker in
           charge, ask for the plain URL and let it answer from the cache. */
        const bust = navigator.serviceWorker && navigator.serviceWorker.controller
            ? '' : '?cb=' + Date.now();
        img.src = IMG_BASE + 'ItemSprites/pokeball.png' + bust;
    });
}

/** True when both the bundles and the sprite folder answered. */
export async function verifyAppData(data: AppData | null): Promise<boolean> {
    const bundlesOk = !!data && data.pokemon.length > 0 && data.items.length > 0;
    return bundlesOk && (await checkAppDataAsset());
}
